name:                haskenthetical
version:             0.1.0.0
github:              "ChickenProp/haskenthetical"
license:             BSD3
author:              "Phil Hazelden"
maintainer:          "philip.hazelden@gmail.com"
copyright:           "2019 Phil Hazelden"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/haskenthetical#readme>

default-extensions:
- GeneralizedNewtypeDeriving
- LambdaCase
- OverloadedStrings

dependencies:
- base >= 4.7 && < 5
- containers
- megaparsec
- text

library:
  source-dirs: src

executables:
  haskenthe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskenthetical

tests:
  haskenthetical-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskenthetical
